package tetris.view;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import tetris.util.Format;

/**
 *
 * @author Jacob Cohen
 */
public class LevelPanel extends javax.swing.JPanel {

	private static final int NUMZEROS = 2;
	private static final long MAX = Format.getMax(NUMZEROS);
	
	private static final long serialVersionUID = -8341632680147599717L;
	
	/** Creates new form LevelPanel */
    public LevelPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        levelLabel = new javax.swing.JLabel();
        levelNumLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(255, 255, 255));
        setToolTipText("");

        levelLabel.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        levelLabel.setForeground(new java.awt.Color(255, 255, 255));
        levelLabel.setText("LEVEL");

        levelNumLabel.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        levelNumLabel.setForeground(new java.awt.Color(255, 255, 255));
        levelNumLabel.setText(Format.formatNumber(0L, NUMZEROS));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(levelLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(levelNumLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(levelLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(levelNumLabel))
        );
    }// </editor-fold>                        

    public void setLevelNum(int levelNum)
    {
    	levelNumLabel.setText(Format.formatNumber(levelNum % MAX, NUMZEROS));
    }
    
    // Variables declaration - do not modify                     
    private javax.swing.JLabel levelLabel;
    private javax.swing.JLabel levelNumLabel;
    // End of variables declaration                   

}
