package tetris.view;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import tetris.util.Format;

/**
 *
 * @author Jacob Cohen
 */
public class LinesPanel extends javax.swing.JPanel {
	
	private static final int NUMZEROS = 3;
	private static final long MAX = Format.getMax(NUMZEROS);

	private static final long serialVersionUID = -2143223560478461930L;
	
	/**
     * Creates new form LinesPanel
     */
    public LinesPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        linesLabel = new javax.swing.JLabel();
        linesNumLabel = new javax.swing.JLabel();
        dashLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));

        linesLabel.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        linesLabel.setForeground(new java.awt.Color(255, 255, 255));
        linesLabel.setText("LINES");

        linesNumLabel.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        linesNumLabel.setForeground(new java.awt.Color(255, 255, 255));
        linesNumLabel.setText(Format.formatNumber(0L, NUMZEROS));

        dashLabel.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        dashLabel.setForeground(new java.awt.Color(255, 255, 255));
        dashLabel.setText("-");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(linesLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dashLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(linesNumLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(linesLabel)
                    .addComponent(dashLabel)
                    .addComponent(linesNumLabel)))
        );
    }// </editor-fold>

    public void setNumLines(int numLines)
    {
    	linesNumLabel.setText(Format.formatNumber(numLines % MAX, NUMZEROS));
    }
    
    // Variables declaration - do not modify                     
    private javax.swing.JLabel dashLabel;
    private javax.swing.JLabel linesLabel;
    private javax.swing.JLabel linesNumLabel;
    // End of variables declaration                   
}
