package tetris.view;

import java.awt.Color;

import tetris.util.Format;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Jacob Cohen
 */
public class ScorePanel extends javax.swing.JPanel {
	private static final int NUMZEROS = 6;
	private static final long MAX = Format.getMax(NUMZEROS);

	private static final long serialVersionUID = 6295804053645580226L;
	
	/**
     * Creates new form ScorePanel
     */
    public ScorePanel(Color background) {
    	setBackground(background);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        topScoreLabel = new javax.swing.JLabel();
        topScoreNumLabel = new javax.swing.JLabel();
        scoreLabel = new javax.swing.JLabel();
        scoreNumLabel = new javax.swing.JLabel();

        topScoreLabel.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        topScoreLabel.setForeground(new java.awt.Color(255, 255, 255));
        topScoreLabel.setText("TOP");

        topScoreNumLabel.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        topScoreNumLabel.setForeground(new java.awt.Color(255, 255, 255));
        topScoreNumLabel.setText(Format.formatNumber(0L, NUMZEROS));

        scoreLabel.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        scoreLabel.setForeground(new java.awt.Color(255, 255, 255));
        scoreLabel.setText("SCORE");

        scoreNumLabel.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        scoreNumLabel.setForeground(new java.awt.Color(255, 255, 255));
        scoreNumLabel.setText(Format.formatNumber(0L, NUMZEROS));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(topScoreLabel)
                    .addComponent(topScoreNumLabel)
                    .addComponent(scoreLabel)
                    .addComponent(scoreNumLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(topScoreLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(topScoreNumLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scoreLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scoreNumLabel))
        );
    }// </editor-fold>
    
    public void setScore(long score)
    {
    	scoreNumLabel.setText(Format.formatNumber(score % MAX, NUMZEROS));
    }
    
    public void setHighScore(long highScore)
    {
    	topScoreNumLabel.setText(Format.formatNumber(highScore % MAX, NUMZEROS));
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel scoreLabel;
    private javax.swing.JLabel scoreNumLabel;
    private javax.swing.JLabel topScoreLabel;
    private javax.swing.JLabel topScoreNumLabel;
    // End of variables declaration                   
}
