package tetris.view;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.Color;

/**
 *
 * @author Jacob Cohen
 */
public class StatisticsPanel extends javax.swing.JPanel {

	private static final long serialVersionUID = -7639703126943265256L;
	
	/**
     * Creates new form StatisticsPanel
     */
    public StatisticsPanel(Color background) {
    	setBackground(background);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        levelLabel = new javax.swing.JLabel();
        levelLabel1 = new javax.swing.JLabel();
        levelLabel2 = new javax.swing.JLabel();
        levelLabel3 = new javax.swing.JLabel();
        levelLabel4 = new javax.swing.JLabel();
        levelLabel5 = new javax.swing.JLabel();
        levelLabel7 = new javax.swing.JLabel();
        levelLabel8 = new javax.swing.JLabel();

        setForeground(new java.awt.Color(255, 255, 255));

        levelLabel.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        levelLabel.setForeground(new java.awt.Color(255, 255, 255));
        levelLabel.setText("000");

        levelLabel1.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        levelLabel1.setForeground(new java.awt.Color(255, 255, 255));
        levelLabel1.setText("STATISTICS");

        levelLabel2.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        levelLabel2.setForeground(new java.awt.Color(255, 255, 255));
        levelLabel2.setText("000");

        levelLabel3.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        levelLabel3.setForeground(new java.awt.Color(255, 255, 255));
        levelLabel3.setText("000");

        levelLabel4.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        levelLabel4.setForeground(new java.awt.Color(255, 255, 255));
        levelLabel4.setText("000");

        levelLabel5.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        levelLabel5.setForeground(new java.awt.Color(255, 255, 255));
        levelLabel5.setText("000");

        levelLabel7.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        levelLabel7.setForeground(new java.awt.Color(255, 255, 255));
        levelLabel7.setText("000");

        levelLabel8.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        levelLabel8.setForeground(new java.awt.Color(255, 255, 255));
        levelLabel8.setText("000");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(levelLabel4)
                        .addComponent(levelLabel2)
                        .addComponent(levelLabel5)
                        .addComponent(levelLabel)
                        .addComponent(levelLabel7)
                        .addComponent(levelLabel8)
                        .addComponent(levelLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(levelLabel1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(levelLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(levelLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(levelLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(levelLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(levelLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(levelLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(levelLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(levelLabel4))
        );
    }// </editor-fold>                        


    // Variables declaration - do not modify                     
    private javax.swing.JLabel levelLabel;
    private javax.swing.JLabel levelLabel1;
    private javax.swing.JLabel levelLabel2;
    private javax.swing.JLabel levelLabel3;
    private javax.swing.JLabel levelLabel4;
    private javax.swing.JLabel levelLabel5;
    private javax.swing.JLabel levelLabel7;
    private javax.swing.JLabel levelLabel8;
    // End of variables declaration                   
}