package tetris.view;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;

import tetris.model.Tetromino;
import tetris.util.Format;

/**
*
* @author Jacob Cohen
*/
public class TetrominoCountPanel extends javax.swing.JPanel {
	
	private static final long serialVersionUID = -9101408505070597354L;
	
	private static final int NUMZEROS = 3;
	private static final long MAX = Format.getMax(NUMZEROS);
	
	private Color background, foreground;
	private Font font;
   
   /**
    * Creates new form TetrominoCountPanel
    */
   public TetrominoCountPanel(Color background, Color foreground, Font font) {
	   this.background = background;
	   this.foreground = foreground;
	   this.font = font;
       initComponents();
   }
   
   public TetrominoCountPanel(Color background)
   {
	   this(background, Color.WHITE, new java.awt.Font("Consolas", 0, 18));
   }
   
   public TetrominoCountPanel()
   {
	   this(Color.BLACK, Color.WHITE, new java.awt.Font("Consolas", 0, 18));
   }
   
   public void setTetromino(Tetromino tetro)
   {
	   tetrominoPanel.setTetromino(tetro);
	   tetrominoPanel.repaint();
   }
   
   public void setCount(int count)
   {
       countLabel.setText(Format.formatNumber(count, MAX, NUMZEROS));
   }
   
   public Dimension getPreferredSize()
   {
	   int height = tetrominoPanel.getPreferredSize().height;
	   height = height > countLabel.getPreferredSize().height ? height : countLabel.getPreferredSize().height;
	   int width = super.getPreferredSize().width;
	   System.out.println(height + ", " + width);
	   return new Dimension(width, height);
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
   private void initComponents() {

       tetrominoPanel = new TetrominoPanel();
       countLabel = new javax.swing.JLabel();

       setBackground(background);

       javax.swing.GroupLayout tetrominoPanelLayout = new javax.swing.GroupLayout(tetrominoPanel);
       tetrominoPanel.setLayout(tetrominoPanelLayout);
       tetrominoPanelLayout.setHorizontalGroup(
           tetrominoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGap(0, 50, Short.MAX_VALUE)
       );
       tetrominoPanelLayout.setVerticalGroup(
           tetrominoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGap(0, 0, Short.MAX_VALUE)
       );

       countLabel.setFont(font); // NOI18N
       countLabel.setForeground(foreground);
       countLabel.setText("000");

       javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
       this.setLayout(layout);
       layout.setHorizontalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addComponent(tetrominoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addComponent(countLabel))
       );
       layout.setVerticalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(countLabel)
               .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
           .addComponent(tetrominoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE, Short.MAX_VALUE)
       );
   }// </editor-fold>                                       


   // Variables declaration - do not modify                     
   private javax.swing.JLabel countLabel;
   private TetrominoPanel tetrominoPanel;
   // End of variables declaration                   
}